### ISSUE TITLE
Example in readme is invalid

### ISSUE THREAD

**Issue by hkdobrev** [dunglas/phpdoc-to-typehint#18]
I don't think it is correct to generate code which will put an argument with a default value before an argument without a default value.

In the example the generated code produces a function like that:

```php
function bar(int $a = null, string $b, bool $c, callable $d = null) : float
```

This means the first argument is optional, but the second and third aren't.

I realise ` = null` is the only way in PHP before 7.1 to specify a type-hinted argument could also be null, but generating such code I think is incorrect.

My suggestion is to never make a parameter without a default value to have one.

When PHP 7.1 is available - #16, the example could be using `?int` which would be correct.

**Comment by dunglas** [comment]
It was a common pattern before 7.1 and it's broadly used in the wild (almost everywhere in the Symfony code base). But it would be - indeed - be better to add support for PHP 7.1 nullable types instead. I definitely agree. Any help to support nullable types is welcome!

**Comment by dereuromark** [comment]
This is indeed an invalid and bad example. That code should never exist (and would be marked as code violation by advanced code sniffer libs like https://github.com/spryker/code-sniffer etc.
A default value before any non optional value is wrong.

Nullable and default null are two different things, often times confused by people.

What you want as result is


Before:

```php
/**
 * @param int|null $a
 * @param string   $b
 * @param bool $c
 * @param callable|null $d
 *
 * @return float
 */
function bar($a, $b, bool $c, callable $d = null)
{
    return 0.0;
}
```

After:

```php
/**
 * @param int|null $a
 * @param string   $b
 * @param bool $c
 * @param callable|null $d
 *
 * @return float
 */
function bar(?int $a, string $b, bool $c, ?callable $d = null) : float
{
    return 0.0;
}
```

Otherwise you just don't typehint $a etc, but keep the "old" syntax in place.
